# Climate Normals 1 (2021-2050): Calculate A and B for Temperature Parameters

To use the AR, lag-1 approach for the non-precipitation parameters, two matrices are required to generate the solution for current values from lag-1 values and error terms. This is part of the weather generator formulation for temperature.

## Matrix Inversion Solutions

\begin{equation*}
    M_{0} = \begin{bmatrix}
                1               & \rho_{0}(1,2)    \\
                \rho_{0}(2,1)   &      1           \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    M_{1} = \begin{bmatrix}
                \rho_{1}(1,1)   & \rho_{1}(1,2)    \\
                \rho_{1}(2,1)   & \rho_{1}(2,2)    \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    A M_{0} = M_{1}
\end{equation*}

\begin{equation*}
    A = M_{0}^{-1} M_{1}
\end{equation*}

\begin{equation*}
    B B^{T} = M_{0} - A M_{1}^{T}
\end{equation*}

Then need to do Cholesky decomposition to get the lower-triangular matrix $B$ from $B B^{T}$

## Parameters and Imports

In [1]:
%matplotlib inline

In [2]:
import os
import pickle
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
OUT_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\CombinedFuture\OtherWeather'

In [4]:
IN_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\CombinedFuture\OtherWeather'

In [5]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho0_2021-2050_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho0Dict = pickle.load( IF )
# end with

In [6]:
BAS_KEYS = sorted( ZTRho0Dict.keys() )

In [7]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho1_2021-2050_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho1Dict = pickle.load( IF )
# end with

### Blanco Basin

In [8]:
bCnt = 0

In [9]:
bas = BAS_KEYS[bCnt]
bas

'Blanco'

In [10]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [11]:
display( HTML( DPrho0DF.to_html() ))

In [12]:
display( HTML( DPrho1DF.to_html() ))

In [13]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [14]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [15]:
A

array([[0.71699582, 0.17336266],
       [0.20229455, 0.66997786]])

In [16]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [17]:
B

array([[0.50482978, 0.        ],
       [0.25870604, 0.47339626]])

### Cibolo Basin

In [18]:
bCnt +=1 

In [19]:
bas = BAS_KEYS[bCnt]
bas

'Cibolo'

In [20]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [21]:
display( HTML( DPrho0DF.to_html() ))

In [22]:
display( HTML( DPrho1DF.to_html() ))

In [23]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [24]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [25]:
A

array([[0.72301182, 0.1686982 ],
       [0.1992355 , 0.67529946]])

In [26]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [27]:
B

array([[0.50264495, 0.        ],
       [0.25162926, 0.47391681]])

### Frio Basin

In [28]:
bCnt +=1 

In [29]:
bas = BAS_KEYS[bCnt]
bas

'Frio'

In [30]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [31]:
display( HTML( DPrho0DF.to_html() ))

In [32]:
display( HTML( DPrho1DF.to_html() ))

In [33]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [34]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [35]:
A

array([[0.73398829, 0.15858553],
       [0.18476558, 0.69389961]])

In [36]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [37]:
B

array([[0.50371697, 0.        ],
       [0.22989443, 0.48023937]])

### Guadalupe Basin

In [38]:
bCnt +=1 

In [39]:
bas = BAS_KEYS[bCnt]
bas

'Guadalupe'

In [40]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [41]:
display( HTML( DPrho0DF.to_html() ))

In [42]:
display( HTML( DPrho1DF.to_html() ))

In [43]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [44]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [45]:
A

array([[0.73092148, 0.15967597],
       [0.20269828, 0.67141384]])

In [46]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [47]:
B

array([[0.50343232, 0.        ],
       [0.25087234, 0.4768017 ]])

### Med-Cib Basin

In [48]:
bCnt +=1 

In [49]:
bas = BAS_KEYS[bCnt]
bas

'Med-Cib'

In [50]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [51]:
display( HTML( DPrho0DF.to_html() ))

In [52]:
display( HTML( DPrho1DF.to_html() ))

In [53]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [54]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [55]:
A

array([[0.72409102, 0.16724998],
       [0.19630609, 0.67808434]])

In [56]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [57]:
B

array([[0.50385008, 0.        ],
       [0.24919783, 0.47590958]])

### Medina Basin

In [58]:
bCnt +=1 

In [59]:
bas = BAS_KEYS[bCnt]
bas

'Medina'

In [60]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [61]:
display( HTML( DPrho0DF.to_html() ))

In [62]:
display( HTML( DPrho1DF.to_html() ))

In [63]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [64]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [65]:
A

array([[0.73111898, 0.15954598],
       [0.19433127, 0.68045499]])

In [66]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [67]:
B

array([[0.50493996, 0.        ],
       [0.24427765, 0.47934632]])

### Nueces Basin

In [68]:
bCnt +=1 

In [69]:
bas = BAS_KEYS[bCnt]
bas

'Nueces'

In [70]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [71]:
display( HTML( DPrho0DF.to_html() ))

In [72]:
display( HTML( DPrho1DF.to_html() ))

In [73]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [74]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [75]:
A

array([[0.74007789, 0.15472264],
       [0.18105987, 0.69934291]])

In [76]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [77]:
B

array([[0.499329  , 0.        ],
       [0.22632027, 0.47849538]])

### Sab-Med Basin

In [78]:
bCnt +=1 

In [79]:
bas = BAS_KEYS[bCnt]
bas

'Sab-Med'

In [80]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [81]:
display( HTML( DPrho0DF.to_html() ))

In [82]:
display( HTML( DPrho1DF.to_html() ))

In [83]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [84]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [85]:
A

array([[0.73038936, 0.16105843],
       [0.18719261, 0.69010287]])

In [86]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [87]:
B

array([[0.50481138, 0.        ],
       [0.237526  , 0.47781573]])

### Sabinal Basin

In [88]:
bCnt +=1 

In [89]:
bas = BAS_KEYS[bCnt]
bas

'Sabinal'

In [90]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [91]:
display( HTML( DPrho0DF.to_html() ))

In [92]:
display( HTML( DPrho1DF.to_html() ))

In [93]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [94]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [95]:
A

array([[0.73216205, 0.15986527],
       [0.18567801, 0.69226018]])

In [96]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [97]:
B

array([[0.50426364, 0.        ],
       [0.23375451, 0.47904671]])