# Custom Climate Normals (2031-2060): Calculate A and B for Temperature Parameters

To use the AR, lag-1 approach for the non-precipitation parameters, two matrices are required to generate the solution for current values from lag-1 values and error terms. This is part of the weather generator formulation for temperature.

## Matrix Inversion Solutions

\begin{equation*}
    M_{0} = \begin{bmatrix}
                1               & \rho_{0}(1,2)    \\
                \rho_{0}(2,1)   &      1           \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    M_{1} = \begin{bmatrix}
                \rho_{1}(1,1)   & \rho_{1}(1,2)    \\
                \rho_{1}(2,1)   & \rho_{1}(2,2)    \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    A M_{0} = M_{1}
\end{equation*}

\begin{equation*}
    A = M_{0}^{-1} M_{1}
\end{equation*}

\begin{equation*}
    B B^{T} = M_{0} - A M_{1}^{T}
\end{equation*}

Then need to do Cholesky decomposition to get the lower-triangular matrix $B$ from $B B^{T}$

## Parameters and Imports

In [1]:
%matplotlib inline

In [2]:
import os
import pickle
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
OUT_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\CombinedFuture\OtherWeather'

In [4]:
IN_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\CombinedFuture\OtherWeather'

In [5]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho0_2031-2060_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho0Dict = pickle.load( IF )
# end with

In [6]:
BAS_KEYS = sorted( ZTRho0Dict.keys() )

In [7]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho1_2031-2060_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho1Dict = pickle.load( IF )
# end with

### Blanco Basin

In [8]:
bCnt = 0

In [9]:
bas = BAS_KEYS[bCnt]
bas

'Blanco'

In [10]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [11]:
display( HTML( DPrho0DF.to_html() ))

In [12]:
display( HTML( DPrho1DF.to_html() ))

In [13]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [14]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [15]:
A

array([[0.72102612, 0.1783692 ],
       [0.21225948, 0.67026246]])

In [16]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [17]:
B

array([[0.4851892 , 0.        ],
       [0.25505994, 0.45291019]])

### Cibolo Basin

In [18]:
bCnt +=1 

In [19]:
bas = BAS_KEYS[bCnt]
bas

'Cibolo'

In [20]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [21]:
display( HTML( DPrho0DF.to_html() ))

In [22]:
display( HTML( DPrho1DF.to_html() ))

In [23]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [24]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [25]:
A

array([[0.72740367, 0.17326056],
       [0.20863461, 0.67518761]])

In [26]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [27]:
B

array([[0.48297985, 0.        ],
       [0.24966185, 0.4541229 ]])

### Frio Basin

In [28]:
bCnt +=1 

In [29]:
bas = BAS_KEYS[bCnt]
bas

'Frio'

In [30]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [31]:
display( HTML( DPrho0DF.to_html() ))

In [32]:
display( HTML( DPrho1DF.to_html() ))

In [33]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [34]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [35]:
A

array([[0.74245581, 0.15927001],
       [0.19092755, 0.69547865]])

In [36]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [37]:
B

array([[0.48306913, 0.        ],
       [0.23114563, 0.46155429]])

### Guadalupe Basin

In [38]:
bCnt +=1 

In [39]:
bas = BAS_KEYS[bCnt]
bas

'Guadalupe'

In [40]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [41]:
display( HTML( DPrho0DF.to_html() ))

In [42]:
display( HTML( DPrho1DF.to_html() ))

In [43]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [44]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [45]:
A

array([[0.73542569, 0.16475854],
       [0.21094808, 0.67332097]])

In [46]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [47]:
B

array([[0.48301369, 0.        ],
       [0.24710825, 0.45623951]])

### Med-Cib Basin

In [48]:
bCnt +=1 

In [49]:
bas = BAS_KEYS[bCnt]
bas

'Med-Cib'

In [50]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [51]:
display( HTML( DPrho0DF.to_html() ))

In [52]:
display( HTML( DPrho1DF.to_html() ))

In [53]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [54]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [55]:
A

array([[0.72982704, 0.17049029],
       [0.20681342, 0.67594006]])

In [56]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [57]:
B

array([[0.48385555, 0.        ],
       [0.24922351, 0.45698978]])

### Medina Basin

In [58]:
bCnt +=1 

In [59]:
bas = BAS_KEYS[bCnt]
bas

'Medina'

In [60]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [61]:
display( HTML( DPrho0DF.to_html() ))

In [62]:
display( HTML( DPrho1DF.to_html() ))

In [63]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [64]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [65]:
A

array([[0.73799803, 0.16236052],
       [0.20466463, 0.67916403]])

In [66]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [67]:
B

array([[0.48376098, 0.        ],
       [0.24280117, 0.46012473]])

### Nueces Basin

In [68]:
bCnt +=1 

In [69]:
bas = BAS_KEYS[bCnt]
bas

'Nueces'

In [70]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [71]:
display( HTML( DPrho0DF.to_html() ))

In [72]:
display( HTML( DPrho1DF.to_html() ))

In [73]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [74]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [75]:
A

array([[0.74712429, 0.15649445],
       [0.18738581, 0.70053342]])

In [76]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [77]:
B

array([[0.47947405, 0.        ],
       [0.2270481 , 0.46061698]])

### Sab-Med Basin

In [78]:
bCnt +=1 

In [79]:
bas = BAS_KEYS[bCnt]
bas

'Sab-Med'

In [80]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [81]:
display( HTML( DPrho0DF.to_html() ))

In [82]:
display( HTML( DPrho1DF.to_html() ))

In [83]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [84]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [85]:
A

array([[0.73866386, 0.1621847 ],
       [0.19798281, 0.68675168]])

In [86]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [87]:
B

array([[0.48382197, 0.        ],
       [0.23831737, 0.46066918]])

### Sabinal Basin

In [88]:
bCnt +=1 

In [89]:
bas = BAS_KEYS[bCnt]
bas

'Sabinal'

In [90]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [91]:
display( HTML( DPrho0DF.to_html() ))

In [92]:
display( HTML( DPrho1DF.to_html() ))

In [93]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [94]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [95]:
A

array([[0.73987311, 0.16159989],
       [0.19302929, 0.69287961]])

In [96]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [97]:
B

array([[0.48332762, 0.        ],
       [0.2340691 , 0.46056869]])