# Historical Observations: Calculate A and B for Temperature Parameters

To use the AR, lag-1 approach for the non-precipitation parameters, two matrices are required to generate the solution for current values from lag-1 values and error terms. This is part of the weather generator formulation for temperature.

## Matrix Inversion Solutions

\begin{equation*}
    M_{0} = \begin{bmatrix}
                1               & \rho_{0}(1,2)    \\
                \rho_{0}(2,1)   &      1           \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    M_{1} = \begin{bmatrix}
                \rho_{1}(1,1)   & \rho_{1}(1,2)    \\
                \rho_{1}(2,1)   & \rho_{1}(2,2)    \\
            \end{bmatrix}
\end{equation*}

\begin{equation*}
    A M_{0} = M_{1}
\end{equation*}

\begin{equation*}
    A = M_{0}^{-1} M_{1}
\end{equation*}

\begin{equation*}
    B B^{T} = M_{0} - A M_{1}^{T}
\end{equation*}

Then need to do Cholesky decomposition to get the lower-triangular matrix $B$ from $B B^{T}$

## Parameters and Imports

In [1]:
%matplotlib inline

In [2]:
import os
import pickle
from IPython.display import display, HTML
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [3]:
OUT_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\Processed_Historical\OtherWeather'

In [4]:
IN_DIR = r'C:\Users\nmartin\Documents\EAA_HCP\Data\SwRI_Processed\Processed_Historical\OtherWeather'

In [5]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho0_1991-2020_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho0Dict = pickle.load( IF )
# end with

In [6]:
BAS_KEYS = sorted( ZTRho0Dict.keys() )

In [7]:
InFiler = os.path.normpath( os.path.join( IN_DIR, "OWeath_Rho1_1991-2020_DFDict.pkl" ) ) 
with open( InFiler, 'rb' ) as IF:
    ZTRho1Dict = pickle.load( IF )
# end with

### Blanco Basin

In [8]:
bCnt = 0

In [9]:
bas = BAS_KEYS[bCnt]
bas

'Blanco'

In [10]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [11]:
display( HTML( DPrho0DF.to_html() ))

In [12]:
display( HTML( DPrho1DF.to_html() ))

In [13]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [14]:
M0

array([[1.        , 0.53105828],
       [0.53105828, 1.        ]])

In [15]:
M1

array([[0.64849432, 0.52624803],
       [0.32444432, 0.67595999]])

In [16]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [17]:
A

array([[ 0.5139801 ,  0.25329464],
       [-0.04809321,  0.70150028]])

In [18]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [19]:
B

array([[0.73033623, 0.        ],
       [0.26437591, 0.6866752 ]])

### Cibolo Basin

In [20]:
bCnt +=1 

In [21]:
bas = BAS_KEYS[bCnt]
bas

'Cibolo'

In [22]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [23]:
display( HTML( DPrho0DF.to_html() ))

In [24]:
display( HTML( DPrho1DF.to_html() ))

In [25]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [26]:
M0

array([[1.        , 0.51849231],
       [0.51849231, 1.        ]])

In [27]:
M1

array([[0.65392483, 0.51158432],
       [0.3247809 , 0.68414468]])

In [28]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [29]:
A

array([[ 0.53157893,  0.23596473],
       [-0.04095222,  0.70537809]])

In [30]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [31]:
B

array([[0.72915806, 0.        ],
       [0.25291034, 0.68319558]])

### Frio Basin

In [32]:
bCnt +=1 

In [33]:
bas = BAS_KEYS[bCnt]
bas

'Frio'

In [34]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [35]:
display( HTML( DPrho0DF.to_html() ))

In [36]:
display( HTML( DPrho1DF.to_html() ))

In [37]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [38]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [39]:
A

array([[ 0.56219295,  0.2050754 ],
       [-0.03543818,  0.68296039]])

In [40]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [41]:
B

array([[0.74093011, 0.        ],
       [0.17681369, 0.72149121]])

### Guadalupe Basin

In [42]:
bCnt +=1 

In [43]:
bas = BAS_KEYS[bCnt]
bas

'Guadalupe'

In [44]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [45]:
display( HTML( DPrho0DF.to_html() ))

In [46]:
display( HTML( DPrho1DF.to_html() ))

In [47]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [48]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [49]:
A

array([[ 0.54429194,  0.22858604],
       [-0.04478881,  0.69200318]])

In [50]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [51]:
B

array([[0.73382846, 0.        ],
       [0.20971313, 0.7094317 ]])

### Med-Cib Basin

In [52]:
bCnt +=1 

In [53]:
bas = BAS_KEYS[bCnt]
bas

'Med-Cib'

In [54]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [55]:
display( HTML( DPrho0DF.to_html() ))

In [56]:
display( HTML( DPrho1DF.to_html() ))

In [57]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [58]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [59]:
A

array([[ 0.5445484 ,  0.21648021],
       [-0.02866402,  0.69770329]])

In [60]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [61]:
B

array([[0.73052685, 0.        ],
       [0.26161958, 0.68176198]])

### Medina Basin

In [62]:
bCnt +=1 

In [63]:
bas = BAS_KEYS[bCnt]
bas

'Medina'

In [64]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [65]:
display( HTML( DPrho0DF.to_html() ))

In [66]:
display( HTML( DPrho1DF.to_html() ))

In [67]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [68]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [69]:
A

array([[ 0.5538868 ,  0.21266316],
       [-0.0370473 ,  0.68672035]])

In [70]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [71]:
B

array([[0.73915485, 0.        ],
       [0.19643863, 0.71442698]])

### Nueces Basin

In [72]:
bCnt +=1 

In [73]:
bas = BAS_KEYS[bCnt]
bas

'Nueces'

In [74]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [75]:
display( HTML( DPrho0DF.to_html() ))

In [76]:
display( HTML( DPrho1DF.to_html() ))

In [77]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [78]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [79]:
A

array([[ 0.56509443,  0.22120385],
       [-0.038851  ,  0.70448358]])

In [80]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [81]:
B

array([[0.71990138, 0.        ],
       [0.19895933, 0.69818032]])

### Sab-Med Basin

In [82]:
bCnt +=1 

In [83]:
bas = BAS_KEYS[bCnt]
bas

'Sab-Med'

In [84]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [85]:
display( HTML( DPrho0DF.to_html() ))

In [86]:
display( HTML( DPrho1DF.to_html() ))

In [87]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [88]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [89]:
A

array([[ 0.57127776,  0.19579602],
       [-0.03851124,  0.69469401]])

In [90]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [91]:
B

array([[0.73505987, 0.        ],
       [0.19766135, 0.70680104]])

### Sabinal Basin

In [92]:
bCnt +=1 

In [93]:
bas = BAS_KEYS[bCnt]
bas

'Sabinal'

In [94]:
DPrho0DF = ZTRho0Dict[bas]
DPrho1DF = ZTRho1Dict[bas]

In [95]:
display( HTML( DPrho0DF.to_html() ))

In [96]:
display( HTML( DPrho1DF.to_html() ))

In [97]:
M0 = DPrho0DF.to_numpy(dtype=np.float64)
M1 = DPrho1DF.to_numpy(dtype=np.float64)

In [98]:
A = np.matmul( M1, np.linalg.inv( M0 ) )

In [99]:
A

array([[ 0.57505088,  0.19625891],
       [-0.03582433,  0.686391  ]])

In [100]:
B = np.linalg.cholesky( M0 - np.matmul( np.matmul( M1, np.linalg.inv( M0 ) ), M1.T ) )

In [101]:
B

array([[0.73450016, 0.        ],
       [0.18187828, 0.71721575]])